server:
  port: 8090
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://zuozhuan.cfd:3307/vue-demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Kpm6skEmiN1
      ## 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      ## 配置获取连接等待超时的时间
      max-wait: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-while-idle: false
      #连接保持空闲而不被驱逐的最小时间
      time-between-eviction-runs-millis: 60000
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: select 1 from DUAL
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      stat-view-servlet:
        # SQL监控后台登录用户名
        login-username: admin
        # SQL监控后台登录用户密码
        login-password: Kpm6skEmiN1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: off