server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zuozhuan.cfd:3307/vue-demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Kpm6skEmiN1
  redis:
    host: 111.119.206.76
    port: 16379
    database: 0
    password: ${spring.datasource.password}
    timeout: 10s
    client-type: lettuce
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 1000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 300
        # 连接池中的最小空闲连接 默认 0
        min-idle: 3
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 1s
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: off
# Knife4j配置
knife4j:
  # 开启增强配置
  enable: true
  #开启Basic登录认证功能
  openapi:
    title: zuozhuanapi
    description: "API文档"
    email: 123456.com
    concat: document  # 作者
    url: http://zuozhuan.cfd
    version: v1.0 # 版本号
    license: Apache 2.0
    license-url: https://fire100.top
    terms-of-service-url: https://fire100.top #API服务条款
auth:
  white_url: /login,/logout,/common/**
  secret: E5tMjwIRQrRdXMVLAzKrQ
